MVC/Models/AdressViewModel.cs
using Sport.Models;
using System.IO;
using System.Reflection.Emit;

namespace MVC.Models
{
    public class AdressViewModel : Adress
    {
        public bool Edit { get; set; }

        //Parameterless constructor
        public AdressViewModel() : this(new Adress())
        {
            Edit = false;
        }

        //Adress constructor
        public AdressViewModel(Adress adress)
        {
            AdressId = adress.AdressId;
            Street = adress.Street;
            StreetNumber = adress.StreetNumber;
            StreetNumberAddition = adress.StreetNumberAddition;
            Zipcode = adress.Zipcode;
            City = adress.City;
            PhoneNumber = adress.PhoneNumber;
            Edit = false;
        }
    }

}

MVC/Controllers/AdressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.Data;
using MVC.Models;
using Sport.Data;
using Sport.Data.Repositories;
using Sport.Models;
using SportData.Data.Domain.Interfaces;

namespace MVC.Controllers
{
    public class AdressController : Controller
    {
        private readonly SportContext _context;
        private readonly IUnitOfWork _unitOfWork;

        public AdressController(SportContext context, IUnitOfWork unitOfWork)
        {
            _context = context;
            _unitOfWork = unitOfWork;
        }

        // GET: _ShowEdit
        public async Task<IActionResult> ShowEdit(int? id)
        {
            if (id == null) return NotFound();

            var viewAdress = (AdressViewModel)_unitOfWork.Adress.Get((int)id);

            if (viewAdress != null)
                return View(viewAdress);
            else
                return NotFound();
        }

        // POST _ShowEdit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ShowEdit([Bind("AdressId,Street,StreetNumber,StreetNumberAddition,Zipcode,City,PhoneNumber,Edit")] AdressViewModel adress)
        {
            if (adress.AdressId == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(adress);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdressExists(adress.AdressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(adress);
        }

        // GET: Adress
        public async Task<IActionResult> Index()
        {
              return _context.Adress != null ? 
                          View(await _context.Adress.ToListAsync()) :
                          Problem("Entity set 'SportContext.Adress'  is null.");
        }

        // GET: Adress/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Adress == null)
            {
                return NotFound();
            }

            var adress = await _context.Adress
                .FirstOrDefaultAsync(m => m.AdressId == id);
            if (adress == null)
            {
                return NotFound();
            }

            return View(adress);
        }

        // GET: Adress/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Adress/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AdressId,Street,StreetNumber,StreetNumberAddition,Zipcode,City,PhoneNumber")] Adress adress)
        {
            if (ModelState.IsValid)
            {
                _context.Add(adress);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(adress);
        }

        // GET: Adress/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Adress == null)
            {
                return NotFound();
            }

            var adress = await _context.Adress.FindAsync(id);
            if (adress == null)
            {
                return NotFound();
            }
            return View(adress);
        }

        // POST: Adress/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AdressId,Street,StreetNumber,StreetNumberAddition,Zipcode,City,PhoneNumber")] Adress adress)
        {
            if (id != adress.AdressId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(adress);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdressExists(adress.AdressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(adress);
        }

        // GET: Adress/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Adress == null)
            {
                return NotFound();
            }

            var adress = await _context.Adress
                .FirstOrDefaultAsync(m => m.AdressId == id);
            if (adress == null)
            {
                return NotFound();
            }

            return View(adress);
        }

        // POST: Adress/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Adress == null)
            {
                return Problem("Entity set 'SportContext.Adress'  is null.");
            }
            var adress = await _context.Adress.FindAsync(id);
            if (adress != null)
            {
                _context.Adress.Remove(adress);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdressExists(int id)
        {
          return (_context.Adress?.Any(e => e.AdressId == id)).GetValueOrDefault();
        }
    }
}

MVC/Views/Adress/Create.cshtml
@model Sport.Models.Adress

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Adress</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetNumber" class="control-label"></label>
                <input asp-for="StreetNumber" class="form-control" />
                <span asp-validation-for="StreetNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetNumberAddition" class="control-label"></label>
                <input asp-for="StreetNumberAddition" class="form-control" />
                <span asp-validation-for="StreetNumberAddition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Adress/Delete.cshtml
@model Sport.Models.Adress

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Adress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetNumberAddition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetNumberAddition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AdressId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC/Views/Adress/Details.cshtml
@model Sport.Models.Adress

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Adress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetNumberAddition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetNumberAddition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AdressId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVC/Views/Adress/Edit.cshtml
@model Sport.Models.Adress

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Adress</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AdressId" />
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetNumber" class="control-label"></label>
                <input asp-for="StreetNumber" class="form-control" />
                <span asp-validation-for="StreetNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetNumberAddition" class="control-label"></label>
                <input asp-for="StreetNumberAddition" class="form-control" />
                <span asp-validation-for="StreetNumberAddition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Adress/Index.cshtml
@model IEnumerable<Sport.Models.Adress>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StreetNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StreetNumberAddition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zipcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Street)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StreetNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StreetNumberAddition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AdressId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AdressId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AdressId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVC/Views/Adress/_ShowEdit.cshtml
@model AdressViewModel

@using (Html.BeginForm("ShowEdit", "Adress", FormMethod.Post))
{
    <div>
        <h5>Adress</h5>
        <hr />
        <form asp-action="ShowEdit" asp-controller="Adress">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AdressId" />
        <dl class="row">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Street)
            </dt>
            <dd class = "col-sm-10">
                @Html.TextBoxFor(model => model.Street,new { @Value = "Street" , @readonly = !Model.Edit })
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.StreetNumber)
            </dt>
            <dd class = "col-sm-10">
                @Html.TextBoxFor(model => model.StreetNumber,new { @Value = "Number", @disabled = !Model.Edit })
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.StreetNumberAddition)
            </dt>
            <dd class = "col-sm-10">
                @Html.TextBoxFor(model => model.StreetNumberAddition,new { @Value = "Addition", @disabled = !Model.Edit })
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Zipcode)
            </dt>
            <dd class = "col-sm-10">
                @Html.TextBoxFor(model => model.Zipcode,new { @Value = "Zipcode", @disabled = !Model.Edit })
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class = "col-sm-10">
                @Html.TextBoxFor(model => model.City,new { @Value = "City", @disabled = !Model.Edit })
            </dd>
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
            <dd class = "col-sm-10">
                @Html.TextBoxFor(model => model.PhoneNumber,new { @Value = "Phonenumber", @disabled = !Model.Edit })
            </dd>
        </dl>
            @{
                string buttonText = Model.Edit ? "Submit" : "Edit";
            }
            <input type="submit" value=@buttonText class="btn btn-primary" />

            </form>
    </div>
}